Add Navie section to the AppMap toolwindow
getappmap/appmap-intellij-plugin pull request #672
Opened 2024-04-22 18:02 UTC by jansorg

Closes https://github.com/getappmap/appmap-intellij-plugin/issues/668

- In a project without AppMaps, a click on "Open instructions" opens the installation guide. Is this still correct?

All panels expanded:
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/bc9d1006-96fd-4507-b988-ff368330226a)
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/37f006ee-bf40-4574-86ff-89e26a7c9ad8)

Default state:
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/63ef91aa-bbf5-4bea-8f7e-a0a6415f4893)
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/add513a9-b62d-4ff5-9c63-4b931cddefab)

Project without AppMaps:
![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/81fe0d5f-8e4e-4c6a-92f3-02fb372f7311)

2024-04-22 19:01 UTC, ahtrotta requested changes
Looks good! There are a few small changes that are needed:

* There's a small spelling mistake where AppMap is Appmap (see comment).
* The `AppMap Data` tool window should be expanded by default, not collapsed.
* Please make the `Create AppMap Data` a blue button in the same style as the `New Navie Chat` button.

Thanks!

2024-04-23 12:56 UTC, jansorg commented
@ahtrotta I've applied the requested changes except for the button.
I've also updated the Navie webvomponent because it was still displaying the red warning about missing AppMaps.
Implementing the button isn't straight-forward, unfortunately. There's not built-in support for it and I'll have to implement a custom Swing component to make this work. I was planning to implement #667 before adding the button.

2024-04-23 16:39 UTC, ahtrotta approved these changes

2024-04-23 16:39 UTC, merged

2024-05-01 21:36 UTC, appland-release commented
:tada: This PR is included in version 0.65.0 :tada:

The release is available on:
- `v0.65.0`
- [GitHub release](https://github.com/getappmap/appmap-intellij-plugin/releases/tag/v0.65.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: