Send project content roots to local AppLand JSON-RPC service
getappmap/appmap-intellij-plugin pull request #673
Opened 2024-04-23 14:12 UTC by jansorg

Closes https://github.com/getappmap/appmap-intellij-plugin/issues/667

This PR implements JSON-RPC message `v2.configuration.set`. 
It send the project's content roots as property `projectDirectories`.

For spring-petclinic the following message is generated:
```json
{
  "jsonrpc": "2.0",
  "method": "v2.configuration.set",
  "params": {
    "projectDirectories": [
      "/sources/spring-petclinic-2023-08-31",
      "/sources/spring-petclinic-2023-08-31/build/generated/aotResources",
      "/sources/spring-petclinic-2023-08-31/build/generated/aotSources",
      "/sources/spring-petclinic-2023-08-31/build/generated/aotTestResources",
      "/sources/spring-petclinic-2023-08-31/build/generated/aotTestSources",
      "/sources/spring-petclinic-2023-08-31/src/main",
      "/sources/spring-petclinic-2023-08-31/src/test"
    ],
    "appmapConfigFiles": [
      "/sources/spring-petclinic-2023-08-31/appmap.yml"
    ]
  }
}
```

2024-04-25 19:43 UTC, ahtrotta requested changes
When I run this in a project with AppMaps, I still see `No AppMap data available` and I don't see any context and Navie answers as if there isn't any context. I verified that this doesn't happen on `develop`.

![image](https://github.com/getappmap/appmap-intellij-plugin/assets/45714532/c8d7f13a-c7b4-46a1-84c2-48be561de1ec)

2024-04-25 19:51 UTC, ahtrotta commented
Also, if you update `@appland/components` to `4.16.1` in `appland-navie`, then you'll be able to see the context in the right-hand side panel in the Navie chat interface.

2024-04-26 08:18 UTC, jansorg commented
I've updated to 4.16.1.
The latest JSON-RPC binary doesn't seem to support v2 yet, but still replies with a 204 status. I can't detect a bad request this way.

2024-04-30 18:06 UTC, jansorg commented
I've fixed the fallback handling, which is now used if the response `status != 2xx` or if the JSON-RPC response contains an error.
I've successfully tested the fallback with [@appland/appmap-v3.136.0](https://github.com/getappmap/appmap-js/releases/tag/%40appland%2Fappmap-v3.136.0).

2024-04-30 19:07 UTC, dustinbyrne approved these changes
The change looks good. I had to run/restart IntelliJ three times for the context to appear to be working though. I'm not sure what that was about. Maybe the CLI hadn't updated?

In any case I was ultimately able to request the configuration from the RPC server launched by the plugin and I can confirm it's getting configured properly.

2024-05-01 08:07 UTC, jansorg commented
> The change looks good. I had to run/restart IntelliJ three times for the context to appear to be working though. I'm not sure what that was about. Maybe the CLI hadn't updated?

It's possible that the CLI wasn't updated yet. The download progress should have been shown in the status bar and the JSON-RPC server would relaunch after the startup.

2024-05-01 18:46 UTC, merged

2024-05-01 21:36 UTC, appland-release commented
:tada: This PR is included in version 0.65.0 :tada:

The release is available on:
- `v0.65.0`
- [GitHub release](https://github.com/getappmap/appmap-intellij-plugin/releases/tag/v0.65.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: